name: Autobus Cycling
favicon: null
layout_spectrum: 0.99553
typography_spectrum: 0.13198
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#ff4f1f'
    - '#ffcc2c'
    - '#909090'
  brandStrength: 0.5568602816201746
  lightness: 0.18935195682570338
  saturation: 0.06724443845450878
  rhythmicContrast: 0.21305111795663834
purpose: []
